---
services:
  nginx:
    build: ./nginx
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/html/intermodular:/var/www/html/intermodular
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/default.conf:/ect/nginx/default.conf
    depends_on:
      - php
    networks:
      default:
        ipv4_address: 10.1.0.20
    dns:
      - 10.1.0.10  

  php:
    build: ./php
    container_name: php-container
    expose:
      - "9000"
    volumes:
      - ./www/html/intermodular:/var/www/html/intermodular
    networks:
      default:
        ipv4_address: 10.1.0.30
    dns:
      - 10.1.0.10

  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: intermodular-gestion-profesores
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password

    volumes:
      # Volumen persistente para los datos de la base de datos
      - mariadb_data:/var/lib/mysql
      # Volumen para scripts de inicialización
      - ./mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 10.1.0.40
    dns:
      - 10.1.0.10 
  dns:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns-container
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
    volumes:
      - ./bind:/etc/bind
    restart: 'always'
    networks:
      default:
        ipv4_address: 10.1.0.10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      default:
        ipv4_address: 10.1.0.50 
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
# Declaración de volúmenes persistentes
volumes:
  mariadb_data:
