server {
    listen 80;
    server_name daw.es www.daw.es despliegue.daw.es www.despliegue.daw.es;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name daw.es www.daw.es despliegue.daw.es www.despliegue.daw.es;

    ssl_certificate     /etc/nginx/ssl/daw.crt;
    ssl_certificate_key /etc/nginx/ssl/daw.key;

    root /var/www/html/intermodular/public;
    index index.php index.html;

    location / {
        proxy_pass http://node-container:4200/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /api {
	    alias /var/www/html/interpodular/puplic;

	    try_files $uri $uri/ /index.php?$query_string;

    	location ~ \.php$ {
        	fastcgi_pass   php-container:9000;
        	fastcgi_index  index.php;
        	fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        	include        fastcgi_params;
    	}
    }

    location ^~ /phpmyadmin/ {
        rewrite ^/phpmyadmin/(.*)$ /$1 break;
        proxy_pass http://phpmyadmin-container:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
